### ISSUE TITLE
display_data: didn't receive the right number of bytes

### ISSUE THREAD

**Issue by occoder** [pklaus/ds1054z#4]
The similar issue occurred on my DS1104Z too.
https://github.com/RoGeorge/DS1054Z_screen_capture/issues/6

**Comment by pklaus** [comment]
Dear @occoder, thank you for your bug report. I updated the firmware of my scope and was able to reproduce it. I fixed this issue with commit 0f1afdb.

This commit is not only fixing the problem but also makes using the `DS1054Z.display_data` property (as well as using the command line tool `ds1054z save-screen <hostname>`) **much faster**. I'm now downloading the screen as PNG image instead of BMP24. The CLI command takes now ~ 8 seconds (PNG) instead of ~ 60 seconds (BMP24) before. (Those values apply when the scope is running - when it's stopped, the transfer is anyhow considerably faster).

I'll publish a new version. For now, I'm closing this pull request. Feel free to reopen or comment if there are still any doubts. And thanks again for reporting.
